// Options the user could type in
let date = new Date();
var currentdate = new Date().toLocaleDateString();
var time = new Date().toLocaleTimeString();
const prompts = [
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may i know your name",
    "what is your name",
    "what call yourself"
  ],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no", "not sure", "maybe", "no thanks"],
  [""],
  ["haha", "ha", "lol", "hehe", "funny", "joke"],
  ["food donate", "project"],
  ["date"],
  ["time"],
  ["what can i donate", "donate"],
  ["trust in madurai", "ngos in madurai"],
  ["tell joke"],
  ["how can I package my cooked or raw food donations", "cooked food donation", "raw food donate"],
  ["how my donation is used"],
  ["can i donate cooked food"],
  ["what are the guidelines for donating"],
  ["What should I enter in the Paper Title field?"],
  ["What should I provide in the Journal Name field?"],
  ["What does Journal Type mean?"],
  ["How should I enter the publication date?"],
  ["What is an ISSN number?"],
  ["Where can I find the ISSN number?"],
  ["What should I upload in the Proof Document field?"],
  ["What does 'Publication Type' mean?"],
  ["What should I enter in the 'Title' field?"],
  ["What should I provide in the 'Publisher Name' field?"],
  ["What is an ISBN number?"],
  ["Where can I find the ISBN number?"],
  ["What should I upload in the 'Proof Document' field?"],
  ["What should I enter in the 'Award Name' field?"],
  ["What should I enter in the 'Award Organization' field?"],
  ["What format should I use for the 'Award Date' field?"],
  ["What should I upload in the 'Proof Document' field?"],
  ["What qualifies as 'Research Funding and Grants'?"],
  ["Who can apply for research funding?"],
  ["What documents are needed to submit a research grant proposal?"],
  ["How do I report funds received for research?"],
  ["What details should I provide for 'Faculty Research Projects'?"],
  ["Are industry-sponsored projects considered under faculty research?"],
  ["What is an 'Industry-Sponsored Project'?"],
  ["What is the purpose of an Incubation Center?"],
  ["Who can use Incubation Centers?"],
  ["What are 'Innovation and Startups' in an academic institution?"],
  ["How do students or faculty members get support for startups?"],
  ["What is an Entrepreneurship Development Program?"],
  ["Who can participate in Entrepreneurship Development Programs?"],
  ["What are extension activities in an academic institution?"],
  ["What is an outreach program, and how is it different from extension activities?"],
  ["How are extension activities documented for NAAC accreditation?"],
  ["What types of awards and recognition are considered under extension activities?"],
  ["How do institutions collaborate with NGOs under extension activities?"],
  ["What are Memorandums of Understanding (MoUs) in academic institutions?"],
  ["Why do institutions sign MoUs with other institutions?"],
  ["What is Industry-Academia collaboration?"],
  ["How does Industry-Academia collaboration benefit students and faculty?"],
  ["What is NAAC?"],
  ["Why is NAAC accreditation important for educational institutions?"],
  ["What are the benefits of NAAC accreditation?"],
  ["How does NAAC evaluate an institution?"],
  ["What is the grading system used by NAAC?"],
  ["What are the different levels of NAAC accreditation?"],
  ["How often does an institution need to apply for NAAC accreditation?"],
  ["What documents are required for NAAC accreditation?"],
  ["What is the Self-Study Report (SSR) in NAAC?"],
  ["What are the seven criteria of NAAC assessment?"],
  ["What is Criterion 1: Curricular Aspects?"],
  ["What is Criterion 2: Teaching-Learning and Evaluation?"],
  ["What is Criterion 3: Research, Innovations, and Extension?"],
  ["What is Criterion 4: Infrastructure and Learning Resources?"],
  ["What is Criterion 5: Student Support and Progression?"],
  ["What is Criterion 6: Governance, Leadership, and Management?"],
  ["What is Criterion 7: Institutional Values and Best Practices?"],
  ["What are the eligibility criteria for NAAC accreditation?"],
  ["What is the role of IQAC (Internal Quality Assurance Cell) in NAAC accreditation?"],
  ["How does NAAC accreditation impact students?"],
  ["What is the DVV (Data Validation and Verification) process in NAAC?"],
  ["How does NAAC assess faculty quality?"],
  ["What are Institutional Social Responsibility (ISR) activities in NAAC?"],
  ["How can an institution improve its NAAC score?"],
  ["What is the difference between NAAC accreditation and NBA accreditation?"],
  ["What is the format of a NAAC peer team visit?"],
  ["How can students contribute to NAAC accreditation?"],
  ["What is the difference between Cycle 1, Cycle 2, and Cycle 3 in NAAC accreditation?"],
  ["What is the role of alumni in NAAC accreditation?"],
  ["What is benchmarking in NAAC accreditation?"],
  ["How do collaborations with industry impact NAAC accreditation?"],
  ["What is the importance of student feedback in NAAC assessment?"],
  ["What are best practices in NAAC accreditation?"],
  ["How does NAAC accreditation affect funding from government bodies?"],
  ["What is the role of ICT (Information and Communication Technology) in NAAC accreditation?"],
  ["How does NAAC accreditation support international recognition of institutions?"],
  ["What are some challenges faced by institutions in NAAC accreditation?"]
]

// Possible responses, in corresponding order

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!", "Howdy"],

  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],

  ["kishor and uppili"],
  ["I am chitti"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  // ["varata mame durr"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok", "I understand", "What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!", "Good one!"],
  ["  The basic concept of this project  Food Waste Management is to collect theexcess/leftover food from donors such as hotels, restaurants, marriage halls, etc and distribute to  the  needy people"],
  [currentdate],
  [time],
  ["you can donate raw ,cooked and packed foods"],
  ["Madurai old age Charitable Trust,208, East Veli Street, Near Keshavan Hospital, "],
  ["joke ha ha .."],
  ["You can package your cooked or raw food donations in airtight containers such as Tupperware or plastic bags. You can also use aluminum foil or cling wrap to keep the food fresh. Please make sure to label the containers with the type of food, date, and any relevant instructions"],
  ["Your donation will be used to support our mission and the various programs and initiatives that we have in place. Your donation will help us to continue providing assistance and support to those in need. You can find more information about our programs and initiatives on our website"],
  ["Yes, you can donate cooked food as long as it is prepared in a licensed kitchen, packaged properly and kept at safe temperatures. Please contact us for further instructions and guidelines"],
  ["When donating raw ingredients, please ensure that the items are unopened and unexpired,"],  
  ["Enter the exact title of your research paper as published in the journal,"],  
  ["Mention the name of the journal where your research paper was published. Example: IEEE Transactions on Computer Science,"],  
  ["It refers to whether the journal is National (published within a country) or International (published globally). Choose the correct option from the dropdown,"],  
  ["Enter the exact date when your paper was published, in the format DD/MM/YYYY,"],  
  ["The ISSN (International Standard Serial Number) is an 8-digit unique code for identifying journals. Example: 1234-5678,"],  
  ["You can find it on the journal’s website, the cover page of the journal, or in the publication details of your research paper,"],  
  ["Upload a PDF or scanned copy of your research paper, journal acceptance letter, or publication certificate as proof,"],  
  ["Select whether you are publishing a complete book or just a chapter within a book,"],  
  ["If you selected 'Book,' enter the book's title. If you selected 'Chapter,' enter the title of the chapter you contributed to,"],  
  ["Enter the name of the publishing house or organization that published the book. Example: Springer, Elsevier, Wiley, Taylor & Francis,"],  
  ["ISBN (International Standard Book Number) is a 13-digit unique code that identifies books. Example: 978-3-16-148410-0,"],  
  ["You can check the book's cover, copyright page, publisher’s website, or book database,"],  
  ["Upload a PDF or scanned copy of any proof, such as: Publication certificate or Acceptance letter or Scanned book page showing your name,"],  
  ["Enter the exact name of the award you received. Example: Best Researcher Award,"],  
  ["Enter the name of the organization or institution that granted the award. Example: IEEE, Springer, Government of India,"],  
  ["Enter the award date in the format dd-mm-yyyy. Example: 15-08-2023,"],  
  ["Upload a PDF or scanned copy of any proof, such as Award certificate or Official letter from the awarding organization or Any document verifying the award,"],  
  ["Research funding and grants refer to financial support provided by institutions, government bodies, or private organizations to conduct research. These funds can be used for equipment, salaries, travel, and publication expenses,"],  
  ["Faculty members, researchers, and sometimes students (with faculty guidance) can apply for research funding, depending on the grant provider's eligibility criteria,"],  
  ["Generally, you need a research proposal, budget estimation, proof of affiliation, previous research work (if applicable), and approval letters from the institution or department,"],  
  ["You should provide details such as the funding agency name, amount received, utilization breakdown, project progress, and any related proof documents like receipts or fund transfer confirmations,"],  
  ["Include project title, funding source, faculty members involved, duration, budget details, objectives, and expected outcomes,"],  
  ["Yes, industry-sponsored projects where external companies provide financial or material support for faculty-led research are included,"],  
  ["It is a research project funded or supported by a company that collaborates with the institution to solve industry-specific problems or develop new technologies,"],  
  ["An Incubation Center is a facility that supports startups and early-stage businesses by providing office space, mentorship, funding opportunities, and networking resources,"],  
  ["Students, faculty members, and entrepreneurs associated with the institution can use incubation centers to develop their business ideas and research into commercial ventures,"],  
  ["Innovation and startups in an academic institution refer to initiatives where students and faculty create new products, services, or businesses using innovative research and ideas,"],  
  ["They can apply for funding, seek mentorship from incubation centers, collaborate with industry experts, and access institutional resources to develop their business,"],  
  ["An Entrepreneurship Development Program (EDP) is a structured initiative that provides training, mentorship, and resources to individuals interested in starting their own businesses,"],  
  ["Students, faculty members, and aspiring entrepreneurs can participate in these programs to gain knowledge on business strategies, financial management, and startup growth,"],  
  ["Extension activities refer to outreach programs conducted by academic institutions to serve society, such as social awareness campaigns, health camps, environmental drives, and skill development programs,"],  
  ["An outreach program is a part of extension activities that focuses on engaging with specific communities or groups outside the institution, such as rural development initiatives or awareness campaigns. Extension activities include broader engagements, including collaborations with NGOs and government agencies,"],  
  ["Institutions document extension activities by maintaining reports, photographs, participation records, impact assessments, and collaboration details with NGOs or other organizations,"],  
  ["Awards and recognition under extension activities include certificates, government acknowledgments, NGO recognitions, and media coverage received for social service programs,"],  
  ["Institutions collaborate with NGOs through joint programs, volunteering opportunities, funding partnerships, and training sessions to address social issues effectively,"],  
  ["Memorandums of Understanding (MoUs) are formal agreements between institutions or organizations to collaborate on academic, research, or development projects,"],  
  ["Institutions sign MoUs to promote knowledge sharing, research collaborations, student exchange programs, and joint training initiatives,"],  
  ["Industry-Academia collaboration refers to partnerships between academic institutions and industries to enhance research, skill development, and job-oriented training,"],  
  ["Such collaborations benefit students by providing internships, research opportunities, and industry exposure, while faculty members gain practical insights and project funding,"],  
  ["Extension activities in an academic institution refer to programs and initiatives undertaken to engage with the community and apply academic knowledge for societal benefit. These activities aim to create social awareness, promote community service, and provide real-world learning experiences for students,"],  
  ["An outreach program is a structured initiative designed to serve the community by providing resources, education, or services, often conducted by students and faculty. The key difference between outreach programs and extension activities is that outreach programs primarily focus on community engagement and social service, whereas extension activities are broader and include applying institutional knowledge to address community issues,"],  
  ["Extension activities are documented for NAAC accreditation by maintaining records such as reports, photographs, attendance lists, impact assessments, and collaboration details with NGOs or government bodies. These records are compiled in the institution’s Self-Study Report (SSR) and presented as part of Criterion 3: Research, Innovations, and Extension,"],  
  ["NAAC (National Assessment and Accreditation Council) is an autonomous body under the University Grants Commission (UGC) responsible for assessing and accrediting higher education institutions in India based on various quality parameters,"],  
  ["NAAC accreditation is important because it helps institutions improve academic quality, secure government funding, enhance student employability, and establish a strong reputation in the education sector,"],  
  ["The benefits of NAAC accreditation include quality assurance, increased funding opportunities, better institutional governance, enhanced student learning outcomes, and improved faculty performance,"],  
  ["NAAC evaluates an institution through a multi-stage process that includes submission of a Self-Study Report (SSR), peer team visits, qualitative and quantitative assessments, and grading based on predefined quality benchmarks,"],  
  ["NAAC uses a grading system ranging from A++ (highest) to D (lowest). The grades are assigned based on the institution’s performance across various assessment criteria,"],  
  ["The different levels of NAAC accreditation are A++, A+, A, B++, B+, B, C, and D. Institutions receiving a grade below C are not accredited,"],  
  ["Institutions must apply for NAAC accreditation every five years, with a reassessment required to maintain or improve their accreditation status,"],  
  ["Documents required for NAAC accreditation include the Self-Study Report (SSR), institutional data, financial records, student and faculty details, and evidence of best practices implemented by the institution,"],  
  ["The Self-Study Report (SSR) is a detailed document prepared by institutions applying for NAAC accreditation. It provides comprehensive information about the institution’s academic and administrative aspects, supported by quantitative and qualitative data,"],  
  ["The seven criteria of NAAC assessment are Curricular Aspects, Teaching-Learning and Evaluation, Research, Innovations and Extension, Infrastructure and Learning Resources, Student Support and Progression, Governance, Leadership and Management, and Institutional Values and Best Practices,"],  
  
]


// Random for any other user input

const alternative = [
  // "Same",
  // "Go on...",
  // "Bro...  i don't know",
  // "Try again",
  // // "I'm listening...:/",
  // "I don't understand ",
  " 😢sorry i am still under development "
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]